services:
  some_wordpress:
    image: wordpress
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=some_myql:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=lmhg
      - WORDPRESS_DB_NAME=modest
  some_myql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lmhg
      - MYSQL_DATABASE=modest